version: '3.4'
services:
  multisma:
    container_name: multisma2
    image: multisma:latest
    network_mode: "host"
    restart: always
    volumes:
      - ./volumes/multisma2/log:/solar/log
      - ./volumes/multisma2/data:/solar/data
